[project]
name = "goit-pythonweb-hw-final"
version = "0.1.0"
description = "REST API додаток для керування контактами користувачів"
authors = [
    {name = "Andrii Veremii",email = "114438382+AndriiVeremi@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"

[tool.poetry]
name = "goit-pythonweb-hw-final"
version = "1.0.0"
description = "REST API додаток для керування контактами користувачів"
authors = ["Andrii Veremii"]
readme = "README.md"
packages = [{include = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
sqlalchemy = "^2.0.23"
alembic = "^1.12.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.0"
pydantic = {extras = ["email"], version = "^2.4.2"}
pydantic-settings = "^2.0.3"
fastapi-limiter = "^0.1.5"
redis = "^5.0.1"
cloudinary = "^1.36.0"
libgravatar = "^1.0.4"
fastapi-mail = "^1.4.1"
apscheduler = "^3.10.4"
slowapi = "^0.1.9"
pyjwt = "^2.10.1"
setuptools = "^78.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
httpx = "^0.25.1"
pytest-cov = "^6.1.0"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.0"
ruff = "^0.1.5"
sphinx = "^7.1.2"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.1.2"
sphinx-rtd-theme = "^1.3.0"
sphinxcontrib-applehelp = "^1.0.4"
sphinxcontrib-devhelp = "^1.0.2"
sphinxcontrib-htmlhelp = "^2.0.1"
sphinxcontrib-jsmath = "^1.0.1"
sphinxcontrib-qthelp = "^1.0.3"
sphinxcontrib-serializinghtml = "^1.1.5"

[tool.poetry.scripts]
test = "pytest:main"
test-cov = "pytest:main --cov=src"
test-v = "pytest:main -v"
test-cov-v = "pytest:main --cov=src -v"

[tool.pytest.ini_options]
addopts = "--doctest-modules -W ignore::DeprecationWarning -W ignore::UserWarning"
testpaths = ["tests"]
pythonpath = "."
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]
asyncio_default_fixture_loop_scope = "function"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.ruff]
line-length = 100
select = ["E", "F", "B", "Q", "I", "W", "PL"]