"""add avatar

Revision ID: 941a67a41c37
Revises: 3477d2f5582f
Create Date: 2025-03-28 18:38:01.388542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941a67a41c37'
down_revision: Union[str, None] = '3477d2f5582f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET confirmed = TRUE WHERE confirmed IS NULL")
    op.alter_column("users", "confirmed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
